import test from 'node:test';
import assert from 'node:assert/strict';

import {
    composeAutogeneratedScreenshotPrompt,
    composeScreenshotGenerationUserPrompt,
    getScreenshotSlotGenerationState,
} from '../utils/screenshot-prompt-workflow.js';

test('composeAutogeneratedScreenshotPrompt injects the inferred theme and title', () => {
    const prompt = composeAutogeneratedScreenshotPrompt({
        appTheme: 'finance dashboards',
        title: 'Track every expense clearly',
    });

    assert.match(prompt, /theme "finance dashboards"/i);
    assert.match(prompt, /Title should say: "Track every expense clearly"/i);
    assert.doesNotMatch(prompt, /APPS_THEME/);
    assert.doesNotMatch(prompt, /SUITING_TITLE/);
});

test('later slots can inherit style from a picked slot 1 screenshot', () => {
    const state = getScreenshotSlotGenerationState({
        slotIndex: 3,
        slotMode: 'simulator',
        isNoBrandMode: true,
        simShotId: 'sim-3',
        brandRefId: null,
        styleRefAssetId: null,
        slotPrompt: '',
        brandPrompt: '',
        slot1PickedAssetId: 'asset-slot-1-picked',
        slot1HasGeneratedOutput: true,
    });

    assert.equal(state.ready, true);
    assert.equal(state.reason, null);
    assert.equal(state.effectiveStyleRefAssetId, 'asset-slot-1-picked');
    assert.equal(state.usesImplicitSlot1Style, true);
});

test('slot 1 is not unblocked by export-icon availability alone', () => {
    const state = getScreenshotSlotGenerationState({
        slotIndex: 1,
        slotMode: 'simulator',
        isNoBrandMode: false,
        simShotId: 'sim-1',
        brandRefId: null,
        styleRefAssetId: null,
        slotPrompt: '',
        brandPrompt: '',
        slot1PickedAssetId: null,
        slot1HasGeneratedOutput: false,
        usesBrandIconColorReference: false,
    });

    assert.equal(state.ready, false);
    assert.equal(state.reason, 'missing_guidance');
    assert.equal(state.usesBrandIconColorReference, false);
});

test('slot 1 can use the picked export icon as color guidance when explicitly enabled', () => {
    const state = getScreenshotSlotGenerationState({
        slotIndex: 1,
        slotMode: 'simulator',
        isNoBrandMode: false,
        simShotId: 'sim-1',
        brandRefId: null,
        styleRefAssetId: null,
        slotPrompt: '',
        brandPrompt: '',
        slot1PickedAssetId: null,
        slot1HasGeneratedOutput: false,
        usesBrandIconColorReference: true,
    });

    assert.equal(state.ready, true);
    assert.equal(state.reason, null);
    assert.equal(state.usesBrandIconColorReference, true);
});

test('later slots are blocked until slot 1 is picked when they have no own guidance', () => {
    const state = getScreenshotSlotGenerationState({
        slotIndex: 2,
        slotMode: 'simulator',
        isNoBrandMode: true,
        simShotId: 'sim-2',
        brandRefId: null,
        styleRefAssetId: null,
        slotPrompt: '',
        brandPrompt: '',
        slot1PickedAssetId: null,
        slot1HasGeneratedOutput: true,
    });

    assert.equal(state.ready, false);
    assert.equal(state.reason, 'pick_slot_1_first');
});

test('later branded slots can also use the picked export icon as color guidance when explicitly enabled', () => {
    const state = getScreenshotSlotGenerationState({
        slotIndex: 2,
        slotMode: 'simulator',
        isNoBrandMode: false,
        simShotId: 'sim-2',
        brandRefId: null,
        styleRefAssetId: null,
        slotPrompt: '',
        brandPrompt: '',
        slot1PickedAssetId: null,
        slot1HasGeneratedOutput: false,
        usesBrandIconColorReference: true,
    });

    assert.equal(state.ready, true);
    assert.equal(state.reason, null);
    assert.equal(state.usesBrandIconColorReference, true);
});

test('a later slot prompt is sufficient guidance even before slot 1 is picked', () => {
    const state = getScreenshotSlotGenerationState({
        slotIndex: 2,
        slotMode: 'simulator',
        isNoBrandMode: true,
        simShotId: 'sim-2',
        brandRefId: null,
        styleRefAssetId: null,
        slotPrompt: 'Keep the headline centered and use soft blue gradients.',
        brandPrompt: '',
        slot1PickedAssetId: null,
        slot1HasGeneratedOutput: true,
    });

    assert.equal(state.ready, true);
    assert.equal(state.reason, null);
    assert.equal(state.effectiveStyleRefAssetId, null);
});

test('brand slots can generate without a simulator screenshot when a slot prompt is present', () => {
    const state = getScreenshotSlotGenerationState({
        slotIndex: 4,
        slotMode: 'brand',
        isNoBrandMode: false,
        simShotId: null,
        brandRefId: null,
        styleRefAssetId: null,
        slotPrompt: 'Create a premium brand slide using the icon palette.',
        brandPrompt: '',
        slot1PickedAssetId: null,
        slot1HasGeneratedOutput: false,
        usesBrandIconColorReference: true,
    });

    assert.equal(state.ready, true);
    assert.equal(state.reason, null);
    assert.equal(state.requiresSimulatorShot, false);
});

test('brand slots require an explicit slot prompt even when icon guidance exists', () => {
    const state = getScreenshotSlotGenerationState({
        slotIndex: 4,
        slotMode: 'brand',
        isNoBrandMode: false,
        simShotId: null,
        brandRefId: null,
        styleRefAssetId: null,
        slotPrompt: '',
        brandPrompt: '',
        slot1PickedAssetId: null,
        slot1HasGeneratedOutput: false,
        usesBrandIconColorReference: true,
    });

    assert.equal(state.ready, false);
    assert.equal(state.reason, 'missing_brand_prompt');
});

test('composeScreenshotGenerationUserPrompt merges branded reference guidance with slot guidance', () => {
    const prompt = composeScreenshotGenerationUserPrompt({
        brandPrompt: 'Keep a calm finance brand aesthetic with soft teal gradients.',
        slotPrompt: 'Title should say: "Track every expense clearly".',
    });

    assert.match(prompt, /calm finance brand aesthetic/i);
    assert.match(prompt, /Track every expense clearly/i);
    assert.match(prompt, /\n\n/);
});
